# Generated by Django 3.2.8 on 2021-10-11 17:00

import LifeSaver.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lungs',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('input_image', models.FileField(blank=True, null=True, upload_to=LifeSaver.utils.get_input_image_path)),
                ('output_image', models.FileField(blank=True, null=True, upload_to=LifeSaver.utils.get_output_image_path)),
                ('verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
